

logging.file: logs/application.log
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR

server:
  port: 8555

spring:
  datasource:
    url:  jdbc:h2:file:./h2/org
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
