
CREATE TABLE PARKING_ORDER(
ID INT NOT NULL  AUTO_INCREMENT PRIMARY KEY,
PARKING_LOG_NAME VARCHAR(255),
CAR_NUMBER VARCHAR(255),
START_TIME TIMESTAMP,
END_TIME TIMESTAMP,
ORDER_STATUS BOOLEAN);

CREATE TABLE PARKING_LOT(
NAME VARCHAR(50) NOT NULL PRIMARY KEY,
CAPACITY INT,
POSITION INT
);

INSERT INTO PARKING_LOT values ('FIRST',20,15);
INSERT INTO PARKING_LOT values ('SECOND',50,25);
INSERT INTO PARKING_LOT values ('THIRD',30,15);

insert into PARKING_ORDER values (0,'FIRST','粤C88888',systimestamp,null,'false');


